version: '2.1'

services:
  glider-dac-providers-app: &provider_anchor
    container_name: glider-dac-providers-app
    restart: always
    build: .
    ports:
      - 3000:5000
    volumes:
      - ./config.local.yml:/glider-dac/config.local.yml
    #  # - .:/glider-dac/  # For local development
      - ./users.db:/glider-dac/users.db

    depends_on:
      - mongo
      - redis

  glider-dac-worker:
    <<: *provider_anchor
    container_name: glider-dac-worker
    command: python glider_dac/worker.py
    ports: []

  glider-dac-watchdog:
    <<: *provider_anchor
    container_name: glider-dac-watchdog
    command: python glider_dac_watchdog.py
    ports: []
    # Update DATA_ROOT to point to ERDDAP directory
    environment:
      - DATA_ROOT=/data/data/priv_erddap
      - FLAGS_DIR=/scratch/tomcat-erddap-private/flag

  qartod_worker_1: &qartod
    build: .
    container_name: qartod_worker_1
    command: python /glider-dac/scripts/glider_qartod.py -w
    volumes:
      - /data/:/data

  qartod_worker_2:
    <<: *qartod
    container_name: qartod_worker_2

  mongo:
    container_name: mongo
    image: mongo:4
    volumes:
      - mongo_storage:/data/db
      - mongo_config:/data/configdb

  # TODO: THREDDS and ERDDAP will need volume configurations
  thredds:
    container_name: thredds
    image: unidata/thredds-docker:5.3
    ports:
      - 8082:8080
    volumes:
      - /data:/data
      - ./docker_contrib/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
      - ./docker_contrib/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml
      - thredds_cache:/usr/local/tomcat/content/thredds/cache
      - thredds_logs:/usr/local/tomcat/content/thredds/logs


  erddap:
    container_name: erddap
    image: axiom/docker-erddap
    ports:
      - 8080:8080

  redis:
    container_name: redis
    restart: always
    image: redis
    volumes:
      - redis_data:/data

volumes:
  thredds_cache:
  thredds_logs:
  mongo_storage:
  mongo_config:
  redis_data:
